### ISSUE TITLE
Cache children selectors

### ISSUE THREAD

**Issue by rafis** [farzher/jQuery-Selector-Cache#2]
I would use this plugin if it would have a feature to cache children selectors. In VanillaJS a dev can query children elements:

```
var holder = document.querySelectorAll('.holder')[0];
var items = holder.querySelectorAll('.item');
```

And same code in jQuery:

```
var $holder = $('.holder').eq(0);
var $items = $('.item', $holder); // or $holder.find('.item')
```

That I need is:

```
var $holder = $$('.holder').eq(0);
var $items = $$('.item', $holder); // or $holder.$$find('item')
```

**Comment by farzher** [comment]
I didn't want to add this because it makes the source code more than twice as big

But it's a useful feature
