### ISSUE TITLE
Can this handle $$(this) inside a $$().each loop?

### ISSUE THREAD

**Issue by danieliser** [farzher/jQuery-Selector-Cache#3]
Wondering how it/you would handle caching of objects inside loops via ```this```?

**Comment by farzher** [comment]
No.

 `$$(this)` never makes sense because `$$` only accepts a string selector.
`$$` is only for finding things, if you already have the thing `this` then you'll have to remember to use `$(this)`

**Comment by danieliser** [comment]
Cool. Was the answer I expected. Was trying to avoid having to instantiate a new jquery object on something that had been cached with $$ further up the call stack.
